#! /bin/csh -f
#SBATCH --time=05:30:00
#SBATCH --job-name=idl
#SBATCH --ntasks=100
#SBATCH --constraint=mil
#SBATCH -A j1008
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH -o IDL2026log-%j.out

##################
# Load the modules
##################

source /usr/share/modules/init/csh
module purge
module load idl/9.1
#module load idl/8.9

limit vmemoryuse unlimited
limit stacksize unlimited

idl run_all_scripts

