#! /bin/csh -f
#SBATCH --time=07:30:00
#SBATCH --job-name=idl
#SBATCH --ntasks=40
#SBATCH --constraint=sky
#SBATCH -A j1008
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH -o IDL2021log-%j.out

##################
# Load the modules
##################

source /usr/share/modules/init/csh
module purge
module load idl/8.5

limit vmemoryuse unlimited
limit stacksize unlimited

idl run_all_scripts

