#!/bin/csh -f

#SBATCH --time=00:30:00
#SBATCH --job-name=python_numba
#SBATCH --ntasks=40
#SBATCH --constraint=sky
#SBATCH -A j1008
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH -o Python2021log_Numba-%j.out


#######################################################################
#                  System Environment Variables
#######################################################################

umask 022

limit

source /usr/share/modules/init/csh
module purge

module load python/GEOSpyD/Min4.9.2_py3.9
#module load python/GEOSpyD/Ana2019.10_py3.7

echo '-------------------------'
echo 'Numba - Copy of matrix'
echo '-------------------------'
python test_copy_matrix_numba.py 5000
python test_copy_matrix_numba.py 7000
python test_copy_matrix_numba.py 9000

echo '-------------------------'
echo 'Numba - matrix multiplication'
echo '-------------------------'
python test_matrix_multiplication_numba.py 1500
python test_matrix_multiplication_numba.py 1750
python test_matrix_multiplication_numba.py 2000

echo '-------------------------'
echo 'Numba Belief Propagation'
echo '-------------------------'
python test_belief_propagation_numba.py 250
python test_belief_propagation_numba.py 500
python test_belief_propagation_numba.py 1000

echo '-------------------------'
echo 'Numba - Fibonacci Sequence'
echo '-------------------------'
python test_fibonacci_numba.py 25
python test_fibonacci_numba.py 35
python test_fibonacci_numba.py 45

echo '-------------------------'
echo 'Numba - Jacobi iterative solver'
echo '-------------------------'
python test_laplace_jacobi_4_numba.py 100
python test_laplace_jacobi_4_numba.py 150
python test_laplace_jacobi_4_numba.py 200

echo '-------------------------'
echo ' Numba Evaluation of functions'
echo '-------------------------'
python test_evaluate_functions_numba.py  80000
python test_evaluate_functions_numba.py  90000
python test_evaluate_functions_numba.py 100000

